// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured for Firebase.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Uf44IhUyxqXCv40RL6f--KrI5Yzjg-o',
    appId: '1:985433556137:web:ee241e1e830c31e4ec55b8',
    messagingSenderId: '985433556137',
    projectId: 'hunarmandkashmir-2c28d',
    authDomain: 'hunarmandkashmir-2c28d.firebaseapp.com',
    storageBucket: 'hunarmandkashmir-2c28d.firebasestorage.app',
    measurementId: 'G-ERWZ928NDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpGtIdOzKWtkaULOkTujnNv4We10jA0o',
    appId: '1:985433556137:android:c769f1ee867eeda5ec55b8',
    messagingSenderId: '985433556137',
    projectId: 'hunarmandkashmir-2c28d',
    storageBucket: 'hunarmandkashmir-2c28d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCWla1UiWPjtW65Z-xlrTjtuTBLIWzQ9E',
    appId: '1:985433556137:ios:58c070ffda1cb972ec55b8',
    messagingSenderId: '985433556137',
    projectId: 'hunarmandkashmir-2c28d',
    storageBucket: 'hunarmandkashmir-2c28d.firebasestorage.app',
    iosBundleId: 'com.example.hunarmandkashmir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCWla1UiWPjtW65Z-xlrTjtuTBLIWzQ9E',
    appId: '1:985433556137:ios:58c070ffda1cb972ec55b8',
    messagingSenderId: '985433556137',
    projectId: 'hunarmandkashmir-2c28d',
    storageBucket: 'hunarmandkashmir-2c28d.firebasestorage.app',
    iosBundleId: 'com.example.hunarmandkashmir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Uf44IhUyxqXCv40RL6f--KrI5Yzjg-o',
    appId: '1:985433556137:web:7688e49b3e214aefec55b8',
    messagingSenderId: '985433556137',
    projectId: 'hunarmandkashmir-2c28d',
    authDomain: 'hunarmandkashmir-2c28d.firebaseapp.com',
    storageBucket: 'hunarmandkashmir-2c28d.firebasestorage.app',
    measurementId: 'G-Z6E2H9CMXC',
  );
}
